export const SIGN_UP_REQUEST   = 'SIGN_UP_REQUEST';
export const SIGN_UP_FAILURE   = 'SIGN_UP_FAILURE';
export const SIGN_UP_SUCCESS   = 'SIGN_UP_SUCCESS';

export const SIGNIN_REQUEST   = 'SIGNIN_REQUEST';
export const SIGNIN_FAILURE   = 'SIGNIN_FAILURE';
export const SIGNIN_SUCCESS   = 'SIGNIN_SUCCESS';

export const LOGGEDIN_REQUEST   = 'LOGGEDIN_REQUEST';
export const LOGGEDIN_FAILURE   = 'LOGGEDIN_FAILURE';
export const LOGGEDIN_SUCCESS   = 'LOGGEDIN_SUCCESS';

export const SIGNOUT_REQUEST   = 'SIGNOUT_REQUEST';
export const SIGNOUT_FAILURE   = 'SIGNOUT_FAILURE';
export const SIGNOUT_SUCCESS   = 'SIGNOUT_SUCCESS';


export const GET_PROFILE_REQUEST   = 'PROFILE_REQUEST';
export const GET_PROFILE_FAILURE   = 'PROFILE_FAILURE';
export const GET_PROFILE_SUCCESS   = 'PROFILE_SUCCESS';

